append-fix

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -12,7 +12,7 @@ inputs:
     description: "The aws-secret-access-key used to authenticate with AWS"
   aws-access-key-id:
     required: true
-    description: "The aws-access-key-id used to authenticate with AWS"  
+    description: "The aws-access-key-id used to authenticate with AWS"
   aws-cluster-name:
     required: true
     description: "The cluster where we want to deploy the app"
@@ -22,7 +22,7 @@ inputs:
   path:
     required: false
     description: "the path of your manifest files"
-    default: .  
+    default: .
 
 runs:
   using: "composite"
@@ -37,46 +37,36 @@ runs:
   - name: update kube config
     shell: bash
     run: aws eks update-kubeconfig --name ${{ inputs.aws-cluster-name }} --region ${{ inputs.aws-region }}
-      
+
   - name: Install kustomize
     shell: bash
     run: |
       curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
       sudo mv kustomize /usr/local/bin/
-     
+
   - name: Create Secret file
+    working-directory: ${{ inputs.path }}
+    shell: bash
     env:
       SECRETS: '${{ inputs.secrets }}'
-    shell: bash
-    working-directory: ${{ inputs.path }}
     run: |
       for secret in $(echo "$SECRETS" | jq -r 'keys[]'); do
-        value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS")"
-        echo "$secret=$value" >> secret.env
+        if [[ "$secret" != "github_token" && ! "$secret" =~ ^AWS_ ]]; then
+          value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS")"
+          echo "$secret=$value" >> secret.env
+        fi
       done
-
-  - name : Check if secret.env is empty
-    working-directory: ${{ inputs.path }}
-    shell: bash
-    run: |
-      if [[ ! -s secret.env ]]; then
-        echo "Warn: secret.env is empty"
-        exit 1
-      fi
+        if [[ ! -s secret.env ]]; then
+          echo "Error: secrets.env is empty"
+          exit 1
+        fi
 
   - name: Append Github Vars to ConfigMap
     working-directory: ${{ inputs.path }}
     env:
       VARS: '${{ inputs.vars }}'
-    shell: bash  
-    run: |
-          for vars in $(echo "$VARS" | jq -r 'keys[]'); do
-            if [[ ! "$vars" =~ ^AWS_ ]]; then
-              value="$(jq -r --arg key "$vars" '.[$key]' <<< "$VARS")"
-              echo -e "\n$vars=$value" >> configmap.env
-            fi
-          done        
-
+    shell: bash
+    run: "for vars in $(echo \"$VARS\" | jq -r 'keys[]'); do\n  if [[ ! \"$vars\" =~ ^AWS_ ]]; then\n    value=\"$(jq -r --arg key \"$vars\" '.[$key]' <<< \"$VARS\")\"\n    echo -e \"\\n$vars=$value\" >> configmap.env\n  fi\ndone        \n    #magic___^_^___line\n"
   - name: Kustomize build & apply
     shell: bash
     run: |
